# Use the public [RubyGems server](http://rubygems.org/)
source                 'https://rubygems.org'

# = Application
# 
# The following dependencies are for your application.
#
# Does one of your processors require the UserAgent library because
# it's parsing HTTP User-Agent strings? Just insert
#
#   gem 'useragent'
#
# here and then remember to run
#
#   $ bundle install --standalone
#
# Here's a link to the [Bundler documentation](http://gembundler.com/)
# for your convenience.

#
# = Framework
#
# The following libraries are part of the deploy pack framework.  You
# shouldn't need to change these.
#

# The core library: processors, dataflows, testing, &c.
#
# Provides
#
#   - wu-local
gem 'wukong',                 :path => '/p/i/wukong'

# Model Hadoop jobs locally and run them on a cluster.
# 
# Provides
#
#   - wu-hadoop
gem 'wukong-hadoop',          '0.1.0'

# Lets Hadoop streaming work with Elasticsearch.
gem 'wonderdog',              '0.1.0'

# Provides an interface into Wukong dataflows accessible from Storm.
#
# Provides
#
#   - wu-storm
gem 'wukong-storm',           '0.1.0'

# Lets you load JSON blobs into data stores.
#
# Provides
#
#   - wu-load
#   - wu-source
gem 'wukong-load',            '0.1.0'

# Framework for gluing code together.
#
# Provides
#
#   - wu-deploy
gem 'wukong-deploy',          '0.1.0'

gem 'wukong-meta', :path => '/p/i/wukong-meta'

group :development do
  gem 'yard'
  gem 'redcarpet'
end

group :test do
  gem 'rspec'
end
